okta - use format_version 3.1.0
Address JSE00001 by incorporating the valid example from package-spec at
https://github.com/elastic/package-spec/blob/ee5775911d6764804548f1f47b479877fbd88d7e/test/packages/good_v3/data_stream/rename_message/elasticsearch/ingest_pipeline/default.yml

```
Error: checking package failed: linting package failed: found 2 validation errors:
   1. file "/Users/akroh/code/elastic/integrations/packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml" is invalid: field processors.133.remove.field: rename "message" to "event.original" processor requires remove "message" processor (JSE00001)
   2. file "/Users/akroh/code/elastic/integrations/packages/okta/data_stream/system/elasticsearch/ingest_pipeline/default.yml" is invalid: field processors.133.remove.if: rename "message" to "event.original" processor requires remove "message" processor with if: 'ctx.event?.original != null' (JSE00001)
```